<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251211210844 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise_muscle (exercise_id INT NOT NULL, muscle_id INT NOT NULL, PRIMARY KEY (exercise_id, muscle_id))');
        $this->addSql('CREATE INDEX IDX_865E8C84E934951A ON exercise_muscle (exercise_id)');
        $this->addSql('CREATE INDEX IDX_865E8C84354FDBB4 ON exercise_muscle (muscle_id)');
        $this->addSql('CREATE TABLE workout (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, endtime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_649FFB727E3C61F9 ON workout (owner_id)');
        $this->addSql('CREATE TABLE workout_exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workout_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_76AB38AAA6CCCFC9 ON workout_exercise (workout_id)');
        $this->addSql('ALTER TABLE exercise_muscle ADD CONSTRAINT FK_865E8C84E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exercise_muscle ADD CONSTRAINT FK_865E8C84354FDBB4 FOREIGN KEY (muscle_id) REFERENCES muscle (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE workout ADD CONSTRAINT FK_649FFB727E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_exercise ADD CONSTRAINT FK_76AB38AAA6CCCFC9 FOREIGN KEY (workout_id) REFERENCES workout (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_muscle DROP CONSTRAINT FK_865E8C84E934951A');
        $this->addSql('ALTER TABLE exercise_muscle DROP CONSTRAINT FK_865E8C84354FDBB4');
        $this->addSql('ALTER TABLE workout DROP CONSTRAINT FK_649FFB727E3C61F9');
        $this->addSql('ALTER TABLE workout_exercise DROP CONSTRAINT FK_76AB38AAA6CCCFC9');
        $this->addSql('DROP TABLE exercise_muscle');
        $this->addSql('DROP TABLE workout');
        $this->addSql('DROP TABLE workout_exercise');
    }
}
